### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by littlebearz**

### CODE REVIEW

**Comment by Zetrith** [comment]
Why is it not fully translated?

**Comment by littlebearz** [comment]
it should be now, I forgot to commit

**Comment by Zetrith** [comment]
Still some things missing
https://github.com/Zetrith/Multiplayer/pull/21/files

**Comment by littlebearz** [comment]
This commit should fix it finally cadb61d02b285f91738384f3ab550c073fb2d98d

**Comment by Zetrith** [comment]
Please open a new pull request with translation only. One change per pull request and the versioning should use 1.0 not 1.0.x anyway (Sorry for the wait)

**Pull request closed without merging**
